### ISSUE TITLE
AttributeError: 'Environment' object has no attribute 'dist_metric'

### ISSUE THREAD

**Issue by caviri** [irmlma/mobility-simulation#1]
Hello @hongyeehh, @sabrinaossey and I are finding the following error when we try to run the tool. Did you find it before? 

Error:
```
root@1830f64ae1c5:/odtp/odtp-workdir/irmlma# python3 mobsim/scripts/run.py 
Traceback (most recent call last):
  File "/odtp/odtp-workdir/irmlma/mobsim/scripts/run.py", line 54, in <module>
    simulator = DTEpr(env)
  File "/usr/local/lib/python3.10/dist-packages/mobsim/models.py", line 222, in __init__
    super().__init__(env, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/mobsim/models.py", line 21, in __init__
    if self.env.dist_metric == "euclidean":
AttributeError: 'Environment' object has no attribute 'dist_metric'
```

Config file:
```
# True reading from db, false reading from data_dir
database: False
# simulated, whether to use simulated or real data
simulated: False

data_dir: "./data/input"
loc_seq_file: "loc_seq.csv"
locs_file: "locs.csv"


# parameters from empirical distribution
wait:
  # could be lognormal, powerlaw or truncpowerlaw 
  type: "lognormal"

  # parameter for lognormal
  mu: 0.75
  sigma: 1.49

  # parameter for both powerlaw (default 1.2) and truncpowerlaw (default 1.1)
  alpha: 1.2

  # parameters for truncpowerlaw
  Lambda: 0.5

jump:
  # could be lognormal, powerlaw or truncpowerlaw 
  type: "lognormal"

  # parameter for lognormal
  mu: 7.72
  sigma: 2.38

  # parameter for both powerlaw (default 1.2) and truncpowerlaw (default 1.1)
  alpha: 1.2

  # parameters for truncpowerlaw
  Lambda: 0.5

rho:
  type: "normal"
  mu: 0.64
  sigma: 0.16

gamma:
  type: "normal"
  mu: 0.18
  sigma: 0.069

# shall be within [0, 1]; change to non 0 value to perform hard interventions
P: 0.0
```

**Comment by caviri** [comment]
Update: I have the same issue when I use the connection to PostgreSQL and the credentials provided.

**Comment by caviri** [comment]
Update: It only works when `database: True, simulated: False`. This is because in `env.py` the only definition for `self.env.dist_metrics` comes after the positive conditional for `database`.

**Comment by hongyeehh** [comment]
Thanks for the bug report, and sorry for the confusion. The code logic got complicated after the database integration.

The parameter allows the user to specify a projected coordinate system of the locations, so the distance calculation can be performed in Euclidian space instead of the much slower Haversine distance. This has now been corrected to the `proj_crs` parameter in the config file. I hope the issue is fixed with the latest code push.

**Comment by caviri** [comment]
Hello @hongyeehh now it works perfect. Thank you a lot for the quick fix.
