### ISSUE TITLE
Running count metric & jump method OverflowError: cannot convert float infinity to integer

### ISSUE THREAD

**Issue by caviri** [irmlma/mobility-simulation#2]
Hello @hongyeehh, I'm getting this error when running Count Metric & Jump Method: 

```
Running count metric & jump method
Values less than or equal to 0 in data. Throwing out 0 or negative values
/usr/local/lib/python3.10/dist-packages/powerlaw.py:1965: RuntimeWarning: divide by zero encountered in scalar divide
  xmax2=xmax/xmin
Traceback (most recent call last):
  File "/odtp/odtp-workdir/mobility-metrics/mobmetric/scripts/run_metrics.py", line 84, in <module>
    powerlaw.plot_pdf(metric, label="data")
  File "/usr/local/lib/python3.10/dist-packages/powerlaw.py", line 2083, in plot_pdf
    edges, hist = pdf(data, linear_bins=linear_bins, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/powerlaw.py", line 1978, in pdf
    number_of_bins = ceil((log_max_size-log_min_size)*10)
OverflowError: cannot convert float infinity to integer
mv: cannot stat '/odtp/odtp-workdir/mobility-metrics/data/output/jump.png': No such file or directory
```

Here, I dropped the input files and the command I'm using: 

```
mobility-metrics/mobmetric/scripts/run_metrics.py count jump dtepr
```
[odtp-output.zip](https://github.com/user-attachments/files/17615294/odtp-output.zip)
[odtp-input.zip](https://github.com/user-attachments/files/17615295/odtp-input.zip)

Version of the tool: https://github.com/irmlma/mobility-metrics/commit/7c1e475940ebf941b788c800685d501d18379c67

**Comment by hongyeehh** [comment]
Hi @caviri, thanks for the report. I was able to reproduce and fix the error. 

The problem comes from [here](https://github.com/irmlma/mobility-metrics/blob/3531dd062d4f6f2343acd7acf446cf98f8d74376/mobmetric/scripts/run_metrics.py#L84), where the calculated metrics contains 0, and the plotting function tries to plot the 0 in log scale. 

This is now fixed by only taking the values larger than `xmin` (default to 1) for plotting. The filter has a negligible effect on the actual results. 

Please check whether the error persists with the latest commit.
